// dim
//
// Generated by shaders/generate.py - do not edit by hand.
// Lowers overall luminance below what the backlight alone can reach, for photosensitivity and very dark rooms.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

void main() {
    vec4 px = texture2D(tex, v_texcoord);
    const float level = 0.55;
    gl_FragColor = vec4(px.rgb * level, px.a);
}
