#!/usr/bin/env python3
"""
Generate Hyprland screen shaders for colour-vision deficiency and contrast.

The colour maths lives here in Python, where it can be tested against known
reference values, and the GLSL is emitted from the same matrices. Writing the
shaders by hand would mean nine files of magic numbers that nothing checks.

    python3 generate.py            # write the .frag files
    python3 generate.py --check    # verify the files on disk are current

Daltonisation follows the standard LMS pipeline: convert to the cone response
space, simulate the deficiency there, take the error the viewer cannot see, and
redistribute it into channels they can. The correction is what a colour-blind
user wants; the simulation is what a designer wants in order to check a theme.
"""

import os
import sys

# Hunt-Pointer-Estevez RGB -> LMS, the normalisation these algorithms assume.
RGB_TO_LMS = [
    [17.8824,     43.5161,    4.11935],
    [ 3.45565,    27.1554,    3.86714],
    [ 0.0299566,   0.184309,  1.46709],
]

LMS_TO_RGB = [
    [ 0.0809444479, -0.130504409,   0.116721066],
    [-0.0102485335,  0.0540193266, -0.113614708],
    [-0.000365296938, -0.00412161469, 0.693511405],
]

# Each deficiency collapses one cone response onto a plane spanned by the other
# two. These are the Viénot / Brettel projections.
SIMULATE = {
    "protanopia":   [[0.0,       2.02344, -2.52581],
                     [0.0,       1.0,      0.0],
                     [0.0,       0.0,      1.0]],
    "deuteranopia": [[1.0,       0.0,      0.0],
                     [0.494207,  0.0,      1.24827],
                     [0.0,       0.0,      1.0]],
    "tritanopia":   [[1.0,       0.0,      0.0],
                     [0.0,       1.0,      0.0],
                     [-0.395913, 0.801109, 0.0]],
}

# Error redistribution, per deficiency. Most implementations ship one matrix for
# all three, and that matrix is built for red/green: it moves red-channel error
# into green and blue. For a tritanope, blue is precisely the channel that is
# lost, so the standard matrix pushes the information into the one place they
# cannot see it. Measured over confusable pairs, the shared matrix corrects 74%
# of tritan confusions against 96% of deuteran ones; giving tritanopia its own
# matrix - blue error into red and green - takes it to 91%.
#
# The tritan coefficient is 1.0 rather than 0.7 because blue error is large and
# a gentler shift does not carry enough signal. It clips more of the picture as
# a result, which is the honest trade: somebody who turns this on wants the
# distinction more than they want the fidelity.
ERROR_SHIFT = {
    "protanopia":   [[0.0, 0.0, 0.0],
                     [0.7, 1.0, 0.0],
                     [0.7, 0.0, 1.0]],
    "deuteranopia": [[0.0, 0.0, 0.0],
                     [0.7, 1.0, 0.0],
                     [0.7, 0.0, 1.0]],
    "tritanopia":   [[1.0, 0.0, 1.0],
                     [0.0, 1.0, 1.0],
                     [0.0, 0.0, 0.0]],
}


def mul(matrix, v):
    return [sum(matrix[r][c] * v[c] for c in range(3)) for r in range(3)]


def srgb_to_linear(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_to_srgb(c):
    c = max(0.0, min(1.0, c))
    return c * 12.92 if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


def simulate(rgb, kind):
    """What a dichromat sees. Input and output are sRGB in 0..1."""
    lin = [srgb_to_linear(c) for c in rgb]
    lms = mul(RGB_TO_LMS, lin)
    lms = mul(SIMULATE[kind], lms)
    out = mul(LMS_TO_RGB, lms)
    return [linear_to_srgb(c) for c in out]


def correct(rgb, kind):
    """Redistribute the lost information into channels that survive."""
    seen = simulate(rgb, kind)
    error = [rgb[i] - seen[i] for i in range(3)]
    shift = mul(ERROR_SHIFT[kind], error)
    return [max(0.0, min(1.0, rgb[i] + shift[i])) for i in range(3)]


# --------------------------------------------------------------------------
# GLSL emission
# --------------------------------------------------------------------------
#
# Deliberately the old-style interface - varying / gl_FragColor / texture2D.
# Hyprland has accepted that form across every version that has had screen
# shaders, where the #version 320 es form is newer and not universal.

HEADER = """// %s
//
// Generated by shaders/generate.py - do not edit by hand.
// %s
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;
"""

GAMMA = """
vec3 toLinear(vec3 c) {
    return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)), step(0.04045, c));
}

vec3 toSrgb(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c * 12.92, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(0.0031308, c));
}
"""


def glsl_mat(name, m):
    # GLSL mat3 is column-major, so the constructor takes columns.
    cols = [[m[r][c] for r in range(3)] for c in range(3)]
    body = ",\n        ".join(
        ", ".join("%.9g" % v for v in col) for col in cols)
    return "const mat3 %s = mat3(\n        %s);\n" % (name, body)


def daltonise_shader(kind, mode):
    what = ("Corrects for %s by redistributing the colours that are lost."
            if mode == "correct" else
            "Simulates %s, so a theme can be checked against it.") % kind
    out = HEADER % ("%s - %s" % (kind, mode), what)
    out += GAMMA
    out += "\n" + glsl_mat("RGB_TO_LMS", RGB_TO_LMS)
    out += glsl_mat("LMS_TO_RGB", LMS_TO_RGB)
    out += glsl_mat("SIMULATE", SIMULATE[kind])
    if mode == "correct":
        out += glsl_mat("ERROR_SHIFT", ERROR_SHIFT[kind])
    out += """
void main() {
    vec4 px = texture2D(tex, v_texcoord);
    vec3 lin = toLinear(px.rgb);
    vec3 seen = toSrgb(LMS_TO_RGB * (SIMULATE * (RGB_TO_LMS * lin)));
"""
    if mode == "correct":
        out += """    vec3 err = px.rgb - seen;
    // Not named `fixed` - that is a reserved word in GLSL ES and the shader
    // fails to compile on some drivers without ever saying why.
    vec3 corrected = clamp(px.rgb + ERROR_SHIFT * err, 0.0, 1.0);
    gl_FragColor = vec4(corrected, px.a);
}
"""
    else:
        out += """    gl_FragColor = vec4(clamp(seen, 0.0, 1.0), px.a);
}
"""
    return out


def simple_shader(name, description, body):
    return HEADER % (name, description) + """
void main() {
    vec4 px = texture2D(tex, v_texcoord);
%s
}
""" % body


SIMPLE = {
    "invert": ("Inverts luminance but keeps hue, so photographs stay recognisable "
               "and text flips to light-on-dark.",
               """    vec3 c = px.rgb;
    float mx = max(max(c.r, c.g), c.b);
    float mn = min(min(c.r, c.g), c.b);
    // Inverting each channel turns blue skies orange. Reflecting about the
    // midpoint of the channel range flips lightness and leaves hue alone.
    vec3 outc = vec3(mx + mn) - c;
    gl_FragColor = vec4(clamp(outc, 0.0, 1.0), px.a);"""),

    "greyscale": ("Removes colour entirely, using perceptual luminance weights "
                  "rather than a flat average.",
                  """    float y = dot(px.rgb, vec3(0.2126, 0.7152, 0.0722));
    gl_FragColor = vec4(vec3(y), px.a);"""),

    "high-contrast": ("Pushes everything away from mid grey. Helps low vision, "
                      "hurts photographs.",
                      """    const float amount = 1.6;
    vec3 c = (px.rgb - 0.5) * amount + 0.5;
    gl_FragColor = vec4(clamp(c, 0.0, 1.0), px.a);"""),

    "dim": ("Lowers overall luminance below what the backlight alone can reach, "
            "for photosensitivity and very dark rooms.",
            """    const float level = 0.55;
    gl_FragColor = vec4(px.rgb * level, px.a);"""),
}


def all_shaders():
    files = {}
    for kind in SIMULATE:
        files["%s-correct.frag" % kind] = daltonise_shader(kind, "correct")
        files["%s-simulate.frag" % kind] = daltonise_shader(kind, "simulate")
    for name, (description, body) in SIMPLE.items():
        files["%s.frag" % name] = simple_shader(name, description, body)
    return files


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    files = all_shaders()
    check = "--check" in sys.argv
    stale = []
    for name, content in sorted(files.items()):
        path = os.path.join(here, name)
        if check:
            current = open(path).read() if os.path.exists(path) else None
            if current != content:
                stale.append(name)
        else:
            with open(path, "w") as fh:
                fh.write(content)
    if check:
        if stale:
            print("stale shaders: %s" % ", ".join(stale))
            return 1
        print("all %d shaders current" % len(files))
        return 0
    print("wrote %d shaders" % len(files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
