// greyscale
//
// Generated by shaders/generate.py - do not edit by hand.
// Removes colour entirely, using perceptual luminance weights rather than a flat average.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

void main() {
    vec4 px = texture2D(tex, v_texcoord);
    float y = dot(px.rgb, vec3(0.2126, 0.7152, 0.0722));
    gl_FragColor = vec4(vec3(y), px.a);
}
