// high-contrast
//
// Generated by shaders/generate.py - do not edit by hand.
// Pushes everything away from mid grey. Helps low vision, hurts photographs.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

void main() {
    vec4 px = texture2D(tex, v_texcoord);
    const float amount = 1.6;
    vec3 c = (px.rgb - 0.5) * amount + 0.5;
    gl_FragColor = vec4(clamp(c, 0.0, 1.0), px.a);
}
