// invert
//
// Generated by shaders/generate.py - do not edit by hand.
// Inverts luminance but keeps hue, so photographs stay recognisable and text flips to light-on-dark.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

void main() {
    vec4 px = texture2D(tex, v_texcoord);
    vec3 c = px.rgb;
    float mx = max(max(c.r, c.g), c.b);
    float mn = min(min(c.r, c.g), c.b);
    // Inverting each channel turns blue skies orange. Reflecting about the
    // midpoint of the channel range flips lightness and leaves hue alone.
    vec3 outc = vec3(mx + mn) - c;
    gl_FragColor = vec4(clamp(outc, 0.0, 1.0), px.a);
}
