// protanopia - correct
//
// Generated by shaders/generate.py - do not edit by hand.
// Corrects for protanopia by redistributing the colours that are lost.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

vec3 toLinear(vec3 c) {
    return mix(c / 12.92, pow((c + 0.055) / 1.055, vec3(2.4)), step(0.04045, c));
}

vec3 toSrgb(vec3 c) {
    c = clamp(c, 0.0, 1.0);
    return mix(c * 12.92, 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055, step(0.0031308, c));
}

const mat3 RGB_TO_LMS = mat3(
        17.8824, 3.45565, 0.0299566,
        43.5161, 27.1554, 0.184309,
        4.11935, 3.86714, 1.46709);
const mat3 LMS_TO_RGB = mat3(
        0.0809444479, -0.0102485335, -0.000365296938,
        -0.130504409, 0.0540193266, -0.00412161469,
        0.116721066, -0.113614708, 0.693511405);
const mat3 SIMULATE = mat3(
        0, 0, 0,
        2.02344, 1, 0,
        -2.52581, 0, 1);
const mat3 ERROR_SHIFT = mat3(
        0, 0.7, 0.7,
        0, 1, 0,
        0, 0, 1);

void main() {
    vec4 px = texture2D(tex, v_texcoord);
    vec3 lin = toLinear(px.rgb);
    vec3 seen = toSrgb(LMS_TO_RGB * (SIMULATE * (RGB_TO_LMS * lin)));
    vec3 err = px.rgb - seen;
    // Not named `fixed` - that is a reserved word in GLSL ES and the shader
    // fails to compile on some drivers without ever saying why.
    vec3 corrected = clamp(px.rgb + ERROR_SHIFT * err, 0.0, 1.0);
    gl_FragColor = vec4(corrected, px.a);
}
